### ISSUE TITLE
Every URL in crunchyroll gets rejected

### ISSUE THREAD

**Issue by DaereanLegrand** [Deathspike/animesync#54]
daerean 雨 ~ ►  animesync download https://www.crunchyroll.com/a-certain-scientific-railgun
[12:49:37] Listening at http://127.0.0.1:6583/
[12:49:37] Checking https://www.crunchyroll.com/a-certain-scientific-railgun
[12:49:38] Rejected https://www.crunchyroll.com/a-certain-scientific-railgun

Tried with different URL's, different account, same error. 

Logs:
```
[12:48:18]` Listening at http://127.0.0.1:6583/
[12:48:18] Checking https://www.crunchyroll.com/a-certain-scientific-railgun
[12:48:18] Rejected https://www.crunchyroll.com/a-certain-scientific-railgun
 daerean 雨 ~ ►  cat animesync/logger/2021-09-25.log
[2021-09-25T17:48:18.122Z] DEBUG Running animesync (2.0.1)
[2021-09-25T17:48:18.123Z] INFO  Listening at http://127.0.0.1:6583/
[2021-09-25T17:48:18.124Z] INFO  Checking https://www.crunchyroll.com/a-certain-scientific-railgun
[2021-09-25T17:48:18.136Z] DEBUG (e127358) HTTP/1.1 POST /api/library
[2021-09-25T17:48:18.144Z] DEBUG (e127360) HTTP/1.1 GET /api/remote/series?url=https%3A%2F%2Fwww.crunchyroll.com%2Fa-certain-scientific-railgun
[2021-09-25T17:48:18.214Z] DEBUG (e127360) HTTP/1.1 200 {"statusCode":500,"message":": Protocol error (Browser.getVersion): Browser closed.\n==================== Browser output: ====================\n<launching> /sbin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/home/daerean/animesync/chrome-data --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://127.0.0.1:6583 --autoplay-policy=no-user-gesture-required --lang=en-US about:blank\n<launched> pid=1404245\n[pid=1404245][err] /usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids\n=========================== logs ===========================\n<launching> /sbin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/home/daerean/animesync/chrome-data --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://127.0.0.1:6583 --autoplay-policy=no-user-gesture-required --lang=en-US about:blank\n<launched> pid=1404245\n[pid=1404245][err] /usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids\n============================================================\n    at captureStackTrace (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/utils/stackTrace.js:60:17)\n    at BrowserType._wrapApiCall (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/client/channelOwner.js:101:58)\n    at BrowserType.launchPersistentContext (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/client/browserType.js:101:17)\n    at BrowserService.launchAsync (/usr/lib/node_modules/animesync/dist/server/shared/services/BrowserService.js:77:63)\n    at BrowserService.pageAsync (/usr/lib/node_modules/animesync/dist/server/shared/services/BrowserService.js:49:94)\n    at Crunchyroll.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/services/crunchyroll/Crunchyroll.js:49:42)\n    at /usr/lib/node_modules/animesync/dist/server/remote/services/ProviderService.js:48:39\n    at async Supervisor.createOrAttachAsync (/usr/lib/node_modules/animesync/dist/server/shared/classes/Supervisor.js:17:16)\n    at async ProviderService.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/services/ProviderService.js:45:16)\n    at async RemoteController.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/RemoteController.js:44:23)"}
[2021-09-25T17:48:18.214Z] ERROR : Protocol error (Browser.getVersion): Browser closed.
==================== Browser output: ====================
<launching> /sbin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/home/daerean/animesync/chrome-data --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://127.0.0.1:6583 --autoplay-policy=no-user-gesture-required --lang=en-US about:blank
<launched> pid=1404245
[pid=1404245][err] /usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids
=========================== logs ===========================
<launching> /sbin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/home/daerean/animesync/chrome-data --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://127.0.0.1:6583 --autoplay-policy=no-user-gesture-required --lang=en-US about:blank
<launched> pid=1404245
[pid=1404245][err] /usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids
============================================================
    at captureStackTrace (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/utils/stackTrace.js:60:17)
    at BrowserType._wrapApiCall (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/client/channelOwner.js:101:58)
    at BrowserType.launchPersistentContext (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/client/browserType.js:101:17)
    at BrowserService.launchAsync (/usr/lib/node_modules/animesync/dist/server/shared/services/BrowserService.js:77:63)
    at BrowserService.pageAsync (/usr/lib/node_modules/animesync/dist/server/shared/services/BrowserService.js:49:94)
    at Crunchyroll.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/services/crunchyroll/Crunchyroll.js:49:42)
    at /usr/lib/node_modules/animesync/dist/server/remote/services/ProviderService.js:48:39
    at async Supervisor.createOrAttachAsync (/usr/lib/node_modules/animesync/dist/server/shared/classes/Supervisor.js:17:16)
    at async ProviderService.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/services/ProviderService.js:45:16)
    at async RemoteController.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/RemoteController.js:44:23)
[2021-09-25T17:48:18.219Z] DEBUG (e127358) HTTP/1.1 204 {"statusCode":500,"message":"HttpException: : Protocol error (Browser.getVersion): Browser closed.\n==================== Browser output: ====================\n<launching> /sbin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/home/daerean/animesync/chrome-data --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://127.0.0.1:6583 --autoplay-policy=no-user-gesture-required --lang=en-US about:blank\n<launched> pid=1404245\n[pid=1404245][err] /usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids\n=========================== logs ===========================\n<launching> /sbin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/home/daerean/animesync/chrome-data --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://127.0.0.1:6583 --autoplay-policy=no-user-gesture-required --lang=en-US about:blank\n<launched> pid=1404245\n[pid=1404245][err] /usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids\n============================================================\n    at captureStackTrace (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/utils/stackTrace.js:60:17)\n    at BrowserType._wrapApiCall (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/client/channelOwner.js:101:58)\n    at BrowserType.launchPersistentContext (/usr/lib/node_modules/animesync/node_modules/playwright-core/lib/client/browserType.js:101:17)\n    at BrowserService.launchAsync (/usr/lib/node_modules/animesync/dist/server/shared/services/BrowserService.js:77:63)\n    at BrowserService.pageAsync (/usr/lib/node_modules/animesync/dist/server/shared/services/BrowserService.js:49:94)\n    at Crunchyroll.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/services/crunchyroll/Crunchyroll.js:49:42)\n    at /usr/lib/node_modules/animesync/dist/server/remote/services/ProviderService.js:48:39\n    at async Supervisor.createOrAttachAsync (/usr/lib/node_modules/animesync/dist/server/shared/classes/Supervisor.js:17:16)\n    at async ProviderService.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/services/ProviderService.js:45:16)\n    at async RemoteController.seriesAsync (/usr/lib/node_modules/animesync/dist/server/remote/RemoteController.js:44:23)\n    at LibraryService.contextPostAsync (/usr/lib/node_modules/animesync/dist/server/library/services/LibraryService.js:67:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async LibraryController.contextPostAsync (/usr/lib/node_modules/animesync/dist/server/library/LibraryController.js:52:9)"}
[2021-09-25T17:48:18.220Z] INFO  Rejected https://www.crunchyroll.com/a-certain-scientific-railgun
```

**Comment by Deathspike** [comment]
It seems that Google Chrome cannot be launched. It looks like it's using Chromium? That's not the same.
Please make sure Google Chrome is installed.

**Comment by DaereanLegrand** [comment]
Oh my bad, i thought it would work with any chromium-based browser.
